CC = gcc
CFLAGS = -Wall -Wextra -O2

all: my_program

# Compile la bibliothèque et le test
test: bigNmb.o tests.o
	$(CC) $(CFLAGS) -o run_tests bigNmb.o tests.o
	./run_tests

bigNmb.o: bigNmb.c bigNmb.h
	$(CC) $(CFLAGS) -c bigNmb.c

tests.o: tests.c bigNmb.h
	$(CC) $(CFLAGS) -c tests.c

clean:
	rm -f *.o run_tests